
package br.com.caelum.estoquews.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstoqueDeItens", targetNamespace = "http://ws.estoque.caelum.com.br/", wsdlLocation = "http://localhost:8080/estoquews-web/EstoqueDeItens?wsdl")
public class EstoqueDeItens
    extends Service
{

    private final static URL ESTOQUEDEITENS_WSDL_LOCATION;
    private final static WebServiceException ESTOQUEDEITENS_EXCEPTION;
    private final static QName ESTOQUEDEITENS_QNAME = new QName("http://ws.estoque.caelum.com.br/", "EstoqueDeItens");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/estoquews-web/EstoqueDeItens?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTOQUEDEITENS_WSDL_LOCATION = url;
        ESTOQUEDEITENS_EXCEPTION = e;
    }

    public EstoqueDeItens() {
        super(__getWsdlLocation(), ESTOQUEDEITENS_QNAME);
    }

    public EstoqueDeItens(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTOQUEDEITENS_QNAME, features);
    }

    public EstoqueDeItens(URL wsdlLocation) {
        super(wsdlLocation, ESTOQUEDEITENS_QNAME);
    }

    public EstoqueDeItens(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTOQUEDEITENS_QNAME, features);
    }

    public EstoqueDeItens(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstoqueDeItens(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort() {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTOQUEDEITENS_EXCEPTION!= null) {
            throw ESTOQUEDEITENS_EXCEPTION;
        }
        return ESTOQUEDEITENS_WSDL_LOCATION;
    }

}
